# Generated by Django 2.0.3 on 2019-01-30 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientName', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('imageUrl', models.CharField(max_length=255)),
            ],
        ),
    ]
