# Generated by Django 2.0.3 on 2019-01-31 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mellow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('imageUrl', models.CharField(max_length=400)),
            ],
        ),
        migrations.AlterField(
            model_name='portfolioitems',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='portfolioitems',
            name='imageUrl',
            field=models.CharField(max_length=400),
        ),
    ]
