# Generated by Django 2.0.3 on 2019-02-07 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mellow', '0002_auto_20190131_0840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioitems',
            name='description',
        ),
        migrations.AddField(
            model_name='employee',
            name='function',
            field=models.CharField(default='default', max_length=255),
        ),
        migrations.AddField(
            model_name='portfolioitems',
            name='mainImageUrl',
            field=models.CharField(default='default url', max_length=400),
        ),
        migrations.AddField(
            model_name='portfolioitems',
            name='request',
            field=models.TextField(default='default'),
        ),
        migrations.AddField(
            model_name='portfolioitems',
            name='siteUrl',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='portfolioitems',
            name='solution',
            field=models.TextField(default='default'),
        ),
        migrations.AddField(
            model_name='portfolioitems',
            name='thumbnail',
            field=models.CharField(default='default url', max_length=400),
        ),
        migrations.AddField(
            model_name='portfolioitems',
            name='title',
            field=models.CharField(default='default', max_length=255),
        ),
        migrations.AlterField(
            model_name='portfolioitems',
            name='clientName',
            field=models.CharField(default='default', max_length=255),
        ),
        migrations.AlterField(
            model_name='portfolioitems',
            name='imageUrl',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
