# Generated by Django 2.0.3 on 2019-02-07 19:16

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('mellow', '0003_auto_20190207_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitems',
            name='request',
            field=tinymce.models.HTMLField(default='default'),
        ),
    ]
