# Generated by Django 2.0.3 on 2019-02-08 08:06

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('mellow', '0004_auto_20190207_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='portfolioitems',
            name='solution',
            field=tinymce.models.HTMLField(default='default'),
        ),
    ]
